.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. driyal_qt test_driyal_qt
clean: FORCE
	$(MAKE) -C .. driyal_qt_clean test_driyal_qt_clean
check: FORCE
	$(MAKE) -C .. test_driyal_qt_check
driyal-qt driyal-qt.exe: FORCE
	 $(MAKE) -C .. driyal_qt
apk: FORCE
	$(MAKE) -C .. driyal_qt_apk
