#ifndef DRIYAL_CHAINPARAMSSEEDS_H
#define DRIYAL_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the driyal network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
};

static const uint8_t chainparams_seed_test[] = {
0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
};
#endif // DRIYAL_CHAINPARAMSSEEDS_H
